name: C/C++ CI

on:
  push:
    branches: [ add_actions_test  ]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: add qt repo
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
        sudo apt-get update -qq
    - name: install qt
      run: |
        sudo apt-get -y install qt511base libgl1-mesa-dev
        source /opt/qt*/bin/qt*-env.sh   
    - name: qmake
      run: qmake
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
