name: C/C++ CI

on:
  push:
    branches: [ add_actions_test  ]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: add qt repo
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
        sudo apt-get update -qq
    - name: install qt
      run:  sudo apt-get -y install qt512base libgl1-mesa-dev
    - name: build
      run: |
        source /opt/qt*/bin/qt*-env.sh || true
        qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        mkdir -p appdir/usr/bin
        cp QTjsonDiff appdir/usr/bin/QTjsonDiff
        mkdir -p appdir/usr/share/icons/
        cp diff.png appdir/usr/share/icons/
        mkdir -p appdir/usr/share/applications/
        cp qtjsondiff.desktop appdir/usr/share/applications/
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
